[package]
name = "example"
version = "0.1.0"
authors = ["justjavac <justjavac@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.90"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"